### ISSUE TITLE
No such module 'CardBuilder'

### ISSUE THREAD

**Issue by ybakos** [mutualmobile/HolidayCard#1]
Thanks for sharing your Hour of Code project.

After building the CardBuilder framework, the main CardPreview project nor the playgrounds can find the CardBuilder framework. Is something mis-configured?

![screen shot 2015-03-12 at 10 22 42 am](https://cloud.githubusercontent.com/assets/5502/6620990/f6d1c530-c8a1-11e4-95f0-061b21284a5a.png)

**Comment by cnstoll** [comment]
Eek. Hoping that the update I just pushed for Swift 2 will fix this on latest tools :(
